<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product>
 */
class ProductFactory extends Factory
{
    protected $model = Product::class;

    public function definition(): array
    {
        $name = trim($this->faker->words($this->faker->numberBetween(2, 4), true));
        $name = ucwords($name);

        $price = $this->faker->randomFloat(2, 9.99, 1999.99);

        $hasDiscount = $this->faker->boolean(30);
        $discountPrice = $hasDiscount
            ? round($price * $this->faker->randomFloat(2, 0.55, 0.9), 2)
            : null;

        $categoryId = Category::query()->inRandomOrder()->value('id');

        return [
            'name' => $name,
            // Slug is auto-generated by the Product model's "saving" hook via SlugService.
            'description' => $this->faker->paragraph($this->faker->numberBetween(2, 4)),
            'price' => $price,
            'discount_price' => $discountPrice,
            'stock' => $this->faker->numberBetween(0, 150),
            'category_id' => $categoryId,
            'image_url' => null,
            'status' => $this->faker->boolean(85) ? 'active' : 'inactive',
        ];
    }

    public function active(): self
    {
        return $this->state(fn () => ['status' => 'active']);
    }

    public function lowStock(): self
    {
        return $this->state(fn () => ['stock' => $this->faker->numberBetween(0, 5)]);
    }
}
